# This is a basic workflow to help you get started with Actions

name: UpdateGithubPagesBranch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-github-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    with:
      ref: github-pages

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        git checkout master preview
        mv preview/* .
        rm -r preview
        git add .
        git commit "[Automatic] Update github-pages according to changes on master"
